### ISSUE TITLE
error on tests

### ISSUE THREAD

**Issue by sselvaggi** [softkraftco/redux-tutorial-how-to-setup-redux#6]
After installing dependencies, when I run tests I get this error:

 FAIL  src/App.test.js
  ✕ renders without crashing (30ms)

  ● renders without crashing

    Invariant Violation: could not find react-redux context value; please ensure the component is wrapped in a <Provider>

       6 | 
       7 | function App() {
    >  8 |   const dispatch = useDispatch()
         |                    ^
       9 |   const { user } = useSelector(state => state.user)
      10 | 
      11 |   if (user) {

      at invariant (node_modules/invariant/invariant.js:40:15)
      at useReduxContext (node_modules/react-redux/lib/hooks/useReduxContext.js:32:29)
      at useStore (node_modules/react-redux/lib/hooks/useStore.js:28:28)
      at useDispatch (node_modules/react-redux/lib/hooks/useDispatch.js:24:17)
      at App (src/App.js:8:20)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:16260:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:18794:13)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:20162:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:336:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:385:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:440:31)
      at beginWork$$1 (node_modules/react-dom/cjs/react-dom.development.js:25780:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:24698:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:24671:22)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:24270:11)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:23698:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:27103:3)
      at node_modules/react-dom/cjs/react-dom.development.js:27528:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:24433:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:27527:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:27608:10)
      at Object.<anonymous> (src/App.test.js:7:12)

  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [Invariant Violation: could not find react-redux context value; please ensure the component is wrapped in a <Provider>]
        at reportException (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:66:24)
        at invokeEventListeners (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:385:16)
        at invokeGuardedCallback (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:440:31)
        at beginWork$$1 (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:25780:7)
        at performUnitOfWork (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:24698:12) Invariant Violation: could not find react-redux context value; please ensure the component is wrapped in a <Provider>
        at invariant (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/invariant/invariant.js:40:15)
        at useReduxContext (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-redux/lib/hooks/useReduxContext.js:32:29)
        at useStore (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-redux/lib/hooks/useStore.js:28:28)
        at useDispatch (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-redux/lib/hooks/useDispatch.js:24:17)
        at App (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/src/App.js:8:20)
        at renderWithHooks (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:16260:18)
        at mountIndeterminateComponent (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:18794:13)
        at beginWork$1 (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:20162:16)
        at HTMLUnknownElement.callCallback (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:336:14)
        at invokeEventListeners (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:385:16)
        at invokeGuardedCallback (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:440:31)
        at beginWork$$1 (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:25780:7)
        at performUnitOfWork (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:24698:12)
        at workLoopSync (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:24671:22)
        at performSyncWorkOnRoot (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:24270:11)
        at scheduleUpdateOnFiber (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:23698:7)
        at updateContainer (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:27103:3)
        at /home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:27528:7
        at unbatchedUpdates (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:24433:12)
        at legacyRenderSubtreeIntoContainer (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:27527:5)
        at Object.render (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/react-dom/cjs/react-dom.development.js:27608:10)
        at Object.<anonymous> (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/src/App.test.js:7:12)
        at Object.asyncJestTest (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
        at /home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jest-jasmine2/build/queueRunner.js:43:12
        at new Promise (<anonymous>)
        at mapper (/home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
        at /home/serg/workspace/rtk-github-issues-example/redux-tutorial-how-to-setup-redux/node_modules/jest-jasmine2/build/queueRunner.js:73:41
        at processTicksAndRejections (internal/process/task_queues.js:93:5) {
      framesToPop: 1
    }

  console.error node_modules/react-dom/cjs/react-dom.development.js:21843
    The above error occurred in the <App> component:
        in App (at App.test.js:7)
    
    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.77s, estimated 2s
Ran all test suites.

Watch Usage: Press w to show more.
Done in 110.05s.

**Comment by kallyas** [comment]
Hav the component wrapped in a provider
